import 'package:assorted_layout_widgets/assorted_layout_widgets.dart';
import 'package:elevarm_ui/elevarm_ui.dart';
import 'package:emp_apnagodam/Domain/Maintenance/CHR/ChrService.dart';
import 'package:emp_apnagodam/Presentation/Constants/ColorConstant.dart';
import 'package:emp_apnagodam/Presentation/Widgets/widgets.dart';
import 'package:emp_apnagodam/Presentation/utils/DynamicShimmerList.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:insta_image_viewer/insta_image_viewer.dart';
import 'package:intl/intl.dart';
import 'package:responsive_sizer/responsive_sizer.dart';
import 'package:searchable_listview/widgets/default_loading_widget.dart';

class CHRCleaningScreen extends ConsumerWidget {
  const CHRCleaningScreen({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    return Scaffold(
      backgroundColor: Colors.white,
      appBar: AppBar(
        centerTitle: true,
        title: Text('CHR'),
        actions: [
          IconButton(
            onPressed: () => context.goNamed('add_chr'),
            icon: Icon(Icons.add),
          ),
        ],
        foregroundColor: Colors.white,
      ),
      body: ref.watch(chrListProvider).when(
            data: (CHRData) {
              return ListView(
                children: [
                  ListView.builder(
                    physics: NeverScrollableScrollPhysics(),
                    shrinkWrap: true,
                    itemCount: CHRData.data?.length ?? 0,
                    itemBuilder: (context, index) {
                      var item = CHRData.data?[index];
                      return Container(
                        child: Column(
                          children: [
                            Padding(
                              padding: const EdgeInsets.all(8.0),
                              child: Column(
                                children: [
                                  Align(
                                    alignment: Alignment.topLeft,
                                    child: Text(
                                      'WareHouse :- ${item?.warehouseName ?? ""}',
                                      overflow: TextOverflow.ellipsis,
                                      style: GoogleFonts.roboto(
                                          color: Color(0xff157173),
                                          fontWeight: FontWeight.w600),
                                    ),
                                  ),
                                  Align(
                                    alignment: Alignment.topLeft,
                                    child: Row(
                                      children: [
                                        Expanded(
                                          child: Column(
                                            mainAxisAlignment:
                                                MainAxisAlignment.start,
                                            crossAxisAlignment:
                                                CrossAxisAlignment.start,
                                            children: [
                                              Text(
                                                'Generated By :- ${item?.userName ?? ""}',
                                                overflow: TextOverflow.ellipsis,
                                                style: GoogleFonts.roboto(),
                                              ),
                                              Text(
                                                'Stack No. :- ${item?.stackNo ?? ""}',
                                                overflow: TextOverflow.ellipsis,
                                                style: GoogleFonts.roboto(),
                                              ),
                                              Text(
                                                'Total Live:- ${item?.live ?? ""}',
                                                overflow: TextOverflow.ellipsis,
                                                style: GoogleFonts.roboto(),
                                              ),
                                            ],
                                          ),
                                        ),
                                        item?.image == null
                                            ? Icon(
                                                Icons.remove_red_eye,
                                                color: primaryColor,
                                              )
                                            : InstaImageViewer(
                                                child: Image.network(
                                                  '${item?.image}',
                                                  fit: BoxFit.cover,
                                                  height: 50,
                                                  loadingBuilder: (context,
                                                          child,
                                                          loadingProgress) =>
                                                      DefaultLoadingWidget(),
                                                  errorBuilder: (BuildContext
                                                          context,
                                                      Object error,
                                                      StackTrace? stackTrace) {
                                                    return Icon(
                                                      Icons
                                                          .image_not_supported_outlined,
                                                      color: primaryColor,
                                                    );
                                                  },
                                                ),
                                              ),
                                      ],
                                    ),
                                  ),

                                  // Row(
                                  //   children: [
                                  //     Expanded(
                                  // child: Text(
                                  //   'Stack No. :- ${item?.stackNo ?? ""}',
                                  //   overflow: TextOverflow.ellipsis,
                                  //   style: GoogleFonts.roboto(),
                                  // ),
                                  //     ),
                                  //     Expanded(
                                  // child: Text(
                                  //   'Total Live:- ${item?.live ?? ""}',
                                  //   overflow: TextOverflow.ellipsis,
                                  //   style: GoogleFonts.roboto(),
                                  // ),
                                  //     ),
                                  //   ],
                                  // ),
                                  Align(
                                    alignment: Alignment.topLeft,
                                    child: Text(
                                      'Remark :- ${item?.remark ?? ""}',
                                      style: GoogleFonts.roboto(),
                                    ),
                                  ),
                                ],
                              ),
                            ),
                            SizedBox(
                              height: 10,
                            ),
                            Container(
                              color: primaryColorDark,
                              padding: const Pad(all: 10),
                              child: IntrinsicHeight(
                                child: Row(children: [
                                  Expanded(
                                    child: Text(
                                      "CHR Date",
                                      textAlign: TextAlign.center,
                                      style: GoogleFonts.roboto(
                                          fontWeight: FontWeight.bold,
                                          color: Colors.white,
                                          fontSize: Adaptive.sp(14)),
                                    ),
                                  ),
                                  const VerticalDivider(),
                                  Expanded(
                                    child: Text(
                                      "Due Date",
                                      textAlign: TextAlign.center,
                                      style: GoogleFonts.roboto(
                                          fontWeight: FontWeight.bold,
                                          color: Colors.white,
                                          fontSize: Adaptive.sp(14)),
                                    ),
                                  ),
                                  const VerticalDivider(),
                                  Expanded(
                                    child: Text(
                                      "Quality Data",
                                      textAlign: TextAlign.center,
                                      style: TextStyle(
                                          fontWeight: FontWeight.bold,
                                          color: Colors.white,
                                          fontSize: Adaptive.sp(14)),
                                    ),
                                  ),
                                  const VerticalDivider(),
                                  Expanded(
                                    child: Text(
                                      "Commodity",
                                      textAlign: TextAlign.center,
                                      style: GoogleFonts.roboto(
                                          fontWeight: FontWeight.bold,
                                          color: Colors.white,
                                          fontSize: Adaptive.sp(14)),
                                    ),
                                  ),
                                ]),
                              ),
                            ),
                            Container(
                              padding: const Pad(all: 10),
                              child: IntrinsicHeight(
                                child: Row(children: [
                                  Expanded(
                                    child: Text(
                                      '${item?.date != null ? DateFormat('dd-MM-yyyy').format(item!.date!) : ""}',
                                      textAlign: TextAlign.center,
                                      style: TextStyle(
                                        fontWeight: FontWeight.bold,
                                        color: Colors.black,
                                        fontSize: Adaptive.sp(14),
                                      ),
                                    ),
                                  ),
                                  const VerticalDivider(),
                                  Expanded(
                                    child: Text(
                                      '${item?.date != null ? DateFormat('dd-MM-yyyy').format(item!.nextDate!) : ""}',
                                      textAlign: TextAlign.center,
                                      style: TextStyle(
                                        fontWeight: FontWeight.bold,
                                        color: Colors.black,
                                        fontSize: Adaptive.sp(14),
                                      ),
                                    ),
                                  ),
                                  const VerticalDivider(),
                                  Expanded(
                                      child: IconButton(
                                          onPressed: () {
                                            showBottomSheet(
                                                context: context,
                                                builder: (bottomsheetContext) =>
                                                   Consumer(builder: (consumerContext,ref,child)=> ElevarmDraggableBottomSheet(
                                                        initialChildSize: 0.7,
                                                        title: 'Quality Data',
                                                        onPressedClose: () {
                                                          Navigator.of(
                                                                  bottomsheetContext)
                                                              .pop();
                                                        },
                                                        children: [
                                                          ref
                                                              .watch(chrQualityPerameterProvider(
                                                                  chrid:
                                                                      "${item?.id}"))
                                                              .when(
                                                                  data:
                                                                      (chrQualityData) =>
                                                                          Column(
                                                                            children: [
                                                                              Container(
                                                                                padding: EdgeInsets.symmetric(vertical: 10),
                                                                                child: Row(
                                                                                  children: [
                                                                                    Expanded(
                                                                                        child: Text(
                                                                                      'Quality data',
                                                                                      textAlign: TextAlign.center,
                                                                                      style: TextStyle(fontWeight: FontWeight.bold, color: Colors.white, fontSize: Adaptive.sp(14)),
                                                                                    )),
                                                                                    const VerticalDivider(),
                                                                                    Expanded(
                                                                                        child: Text(
                                                                                      'Value',
                                                                                      textAlign: TextAlign.center,
                                                                                      style: TextStyle(fontWeight: FontWeight.bold, color: Colors.white, fontSize: Adaptive.sp(14)),
                                                                                    )),
                                                                                  ],
                                                                                ),
                                                                                decoration: BoxDecoration(color: Color(0xff157173), borderRadius: BorderRadius.only(topLeft: Radius.circular(10), topRight: Radius.circular(10))),
                                                                              ),
                                                                              ListView.builder(
                                                                                physics: NeverScrollableScrollPhysics(),
                                                                                shrinkWrap: true,
                                                                                itemCount: chrQualityData.data?.length ?? 0,
                                                                                itemBuilder: (context, index) {
                                                                                  return Container(
                                                                                    color: index % 2 == 0 ? Colors.grey.withOpacity(0.2) : Colors.white,
                                                                                    child: Row(
                                                                                      children: [
                                                                                        Expanded(
                                                                                            child: Text(
                                                                                          '${chrQualityData.data?[index].parameter}',
                                                                                          textAlign: TextAlign.center,
                                                                                          style: TextStyle(fontWeight: FontWeight.bold, color: Colors.black, fontSize: Adaptive.sp(14)),
                                                                                        )),
                                                                                        SizedBox(
                                                                                          child: const VerticalDivider(
                                                                                            color: Colors.black,
                                                                                          ),
                                                                                          height: 40,
                                                                                        ),
                                                                                        Expanded(
                                                                                            child: Text(
                                                                                          '${chrQualityData.data?[index].value}',
                                                                                          textAlign: TextAlign.center,
                                                                                          style: TextStyle(fontWeight: FontWeight.bold, color: Colors.black, fontSize: Adaptive.sp(14)),
                                                                                        )),
                                                                                      ],
                                                                                    ),
                                                                                  );
                                                                                },
                                                                              )
                                                                            ],
                                                                          ),
                                                                  error: (e,
                                                                          s) =>
                                                                      Container(),
                                                                  loading: () =>
                                                                      DynamicShimmerList())
                                                        ])));
                                          },
                                          icon: Icon(
                                            Icons.remove_red_eye,
                                            color: Color(0xff157173),
                                          ))),
                                  const VerticalDivider(),
                                  Expanded(
                                    child: Text(
                                      '${item?.commodity ?? "--"}',
                                      textAlign: TextAlign.center,
                                      style: TextStyle(
                                          fontWeight: FontWeight.bold,
                                          color: Colors.black,
                                          fontSize: Adaptive.sp(14)),
                                    ),
                                  ),
                                ]),
                              ),
                            ),
                          ],
                        ),
                        margin: EdgeInsets.all(10),
                        decoration: BoxDecoration(
                          border: Border.all(color: Color(0xff157173)),
                          borderRadius: BorderRadius.circular(10),
                        ),
                      );
                    },
                  ),
                ],
              );
            },
            error: (e, s) => Text(''),
            loading: () => loader(context),
          ),
    );
  }
}
