import 'package:assorted_layout_widgets/assorted_layout_widgets.dart';
import 'package:emp_apnagodam/Domain/Maintenance/Cleaning/CleaningService.dart';
import 'package:emp_apnagodam/Presentation/Constants/ColorConstant.dart';
import 'package:emp_apnagodam/Presentation/Widgets/widgets.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import 'package:insta_image_viewer/insta_image_viewer.dart';
import 'package:responsive_sizer/responsive_sizer.dart';

class CleaningScreenPage extends ConsumerStatefulWidget {
  const CleaningScreenPage({
    super.key,
  });

  @override
  ConsumerState<CleaningScreenPage> createState() => _LockAndKeyScreenState();
}

class _LockAndKeyScreenState extends ConsumerState<CleaningScreenPage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.white,
      appBar: AppBar(
        centerTitle: true,
        title: Text('Cleaning'),
        actions: [
          IconButton(
              onPressed: () => context.goNamed('add_cleaning'),
              icon: Icon(Icons.add))
        ],
        foregroundColor: Colors.white,
      ),
      body: ref.watch(cleaningListProvider).when(
          data: (CleaningData) => (CleaningData.data ?? []).isEmpty
              ? Container(
                  height: MediaQuery.of(context).size.height,
                  alignment: Alignment.center,
                  child: noItems('Cleaning', context),
                )
              : ListView(
                  children: [
                    ListView.builder(
                      itemCount: CleaningData.data?.length ?? 0,
                      physics: NeverScrollableScrollPhysics(),
                      shrinkWrap: true,
                      itemBuilder: (context, index) {
                        return Container(
                          child: Column(
                            children: [
                              Padding(
                                padding: const EdgeInsets.all(8.0),
                                child: Column(
                                  children: [
                                    Align(
                                        alignment: Alignment.topLeft,
                                        child: Text(
                                          'WareHouse :- ${CleaningData.data?[index].warehouseName ?? ""}',
                                          overflow: TextOverflow.ellipsis,
                                          style: TextStyle(
                                              color: Color(0xff157173),
                                              fontWeight: FontWeight.w600),
                                        )),
                                    SizedBox(
                                      height: 10,
                                    ),
                                    Align(
                                        alignment: Alignment.topLeft,
                                        child: Text(
                                          'Generated By :- ${CleaningData.data?[index].userName ?? ""}',
                                          overflow: TextOverflow.ellipsis,
                                          style: TextStyle(),
                                        )),
                                  ],
                                ),
                              ),
                              SizedBox(
                                height: 10,
                              ),
                              Container(
                                color: primaryColorDark,
                                padding: const Pad(all: 10),
                                child: IntrinsicHeight(
                                  child: Row(children: [
                                    Expanded(
                                        child: Text(
                                      "Cleaning Date",
                                      textAlign: TextAlign.center,
                                      style: TextStyle(
                                          fontWeight: FontWeight.bold,
                                          color: Colors.white,
                                          fontSize: Adaptive.sp(14)),
                                    )),
                                    const VerticalDivider(),
                                    Expanded(
                                        child: Text(
                                      "Due Date",
                                      textAlign: TextAlign.center,
                                      style: TextStyle(
                                          fontWeight: FontWeight.bold,
                                          color: Colors.white,
                                          fontSize: Adaptive.sp(14)),
                                    )),
                                    const VerticalDivider(),
                                    Expanded(
                                        child: Text(
                                      "Remark",
                                      textAlign: TextAlign.center,
                                      style: TextStyle(
                                          fontWeight: FontWeight.bold,
                                          color: Colors.white,
                                          fontSize: Adaptive.sp(14)),
                                    )),
                                    const VerticalDivider(),
                                    Expanded(
                                        child: Text(
                                      "Image",
                                      textAlign: TextAlign.center,
                                      style: TextStyle(
                                          fontWeight: FontWeight.bold,
                                          color: Colors.white,
                                          fontSize: Adaptive.sp(14)),
                                    )),
                                  ]),
                                ),
                              ),
                              Container(
                                padding: EdgeInsets.symmetric(vertical: 7),
                                child: IntrinsicHeight(
                                  child: Row(children: [
                                    Expanded(
                                        child: Text(
                                      '${CleaningData.data?[index].date}'
                                          .substring(0, 10),
                                      textAlign: TextAlign.center,
                                      style: TextStyle(
                                          fontWeight: FontWeight.bold,
                                          color: Colors.black,
                                          fontSize: Adaptive.sp(14)),
                                    )),
                                    const VerticalDivider(),
                                    Expanded(
                                        child: Text(
                                      '${CleaningData.data?[index].nextDate}'
                                          .substring(0, 10),
                                      textAlign: TextAlign.center,
                                      style: TextStyle(
                                          fontWeight: FontWeight.bold,
                                          color: Colors.black,
                                          fontSize: Adaptive.sp(14)),
                                    )),
                                    const VerticalDivider(),
                                    Expanded(
                                        child: Text(
                                      '${CleaningData.data?[index].remark}',
                                      textAlign: TextAlign.center,
                                      style: TextStyle(
                                          fontWeight: FontWeight.bold,
                                          color: Colors.black,
                                          fontSize: Adaptive.sp(14)),
                                    )),
                                    const VerticalDivider(),
                                    Expanded(
                                      child: CleaningData.data?[index].image ==
                                                  null ||
                                              CleaningData
                                                  .data?[index].image.isEmpty
                                          ? Icon(
                                              Icons.remove_red_eye,
                                              color: Color(0xff157173),
                                            )
                                          : InstaImageViewer(
                                              child: Image.network(
                                                '${CleaningData.data?[index].image}',
                                                fit: BoxFit.contain,
                                                height: 40,
                                                loadingBuilder: (
                                                  BuildContext context,
                                                  Widget child,
                                                  ImageChunkEvent?
                                                      loadingProgress,
                                                ) {
                                                  if (loadingProgress == null) {
                                                    return child;
                                                  } else {
                                                    return Center(
                                                      child:
                                                          CircularProgressIndicator(),
                                                    );
                                                  }
                                                },
                                                errorBuilder: (
                                                  BuildContext context,
                                                  Object error,
                                                  StackTrace? stackTrace,
                                                ) {
                                                  return Icon(
                                                    Icons
                                                        .image_not_supported_outlined,
                                                    color: Colors.red,
                                                  );
                                                },
                                              ),
                                            ),
                                    ),
                                  ]),
                                ),
                              ),
                            ],
                          ),
                          // padding: EdgeInsets.all(10),
                          margin: EdgeInsets.all(10),
                          decoration: BoxDecoration(
                            border: Border.all(color: Color(0xff157173)),
                            borderRadius: BorderRadius.circular(10),
                          ),
                        );
                      },
                    )
                  ],
                ),
          error: (e, s) => Text(''),
          loading: () => loader(context)),
    );
  }
}
