import 'package:assorted_layout_widgets/assorted_layout_widgets.dart';
import 'package:emp_apnagodam/Domain/Maintenance/Spray/SprayService.dart';
import 'package:emp_apnagodam/Domain/dio/DioProvider.dart';
import 'package:emp_apnagodam/Presentation/Constants/ColorConstant.dart';
import 'package:emp_apnagodam/Presentation/Widgets/widgets.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import 'package:responsive_sizer/responsive_sizer.dart';

import '../../Widgets/GenericImageLoader.dart';

class SprayCleaningScreen extends ConsumerWidget {
  const SprayCleaningScreen({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    return Scaffold(
      backgroundColor: Colors.white,
      appBar: AppBar(
        centerTitle: true,
        title: Text('Spray'),
        actions: [
          IconButton(
              onPressed: () => context.goNamed('add_spray'),
              icon: Icon(Icons.add))
        ],
        foregroundColor: Colors.white,
      ),
      body: ref.watch(sprayListProvider).when(
          data: (sprayData) => (sprayData.data ?? []).isEmpty
              ? Container(
                  height: MediaQuery.of(context).size.height,
                  alignment: Alignment.center,
                  child: noItems('Spray', context),
                )
              : ListView(
                  children: [
                    ListView.builder(
                      itemCount: sprayData.data?.length ?? 0,
                      physics: NeverScrollableScrollPhysics(),
                      shrinkWrap: true,
                      itemBuilder: (context, index) {
                        return Container(
                          child: Column(
                            children: [
                              Padding(
                                padding: const EdgeInsets.all(8.0),
                                child: Column(
                                  children: [
                                    Align(
                                        alignment: Alignment.topLeft,
                                        child: Text(
                                          'WareHouse :- ${sprayData.data?[index].warehouseName?.name ?? ""}',
                                          overflow: TextOverflow.ellipsis,
                                          style: TextStyle(
                                              color: Color(0xff157173),
                                              fontWeight: FontWeight.w600),
                                        )),
                                    Align(
                                        alignment: Alignment.topLeft,
                                        child: Row(
                                          mainAxisAlignment:
                                              MainAxisAlignment.spaceBetween,
                                          children: [
                                            Expanded(
                                              child: Column(
                                                mainAxisAlignment:
                                                    MainAxisAlignment.start,
                                                crossAxisAlignment:
                                                    CrossAxisAlignment.start,
                                                children: [
                                                  Text(
                                                    'Generated By :- ${sprayData.data?[index].userName?.fname + "  " + sprayData.data?[index].userName?.lname ?? ""}',
                                                    overflow:
                                                        TextOverflow.ellipsis,
                                                    style: TextStyle(),
                                                  ),
                                                  Text(
                                                    'Remark :- ${sprayData.data?[index].remark}',
                                                    overflow:
                                                        TextOverflow.ellipsis,
                                                  ),
                                                ],
                                              ),
                                            ),
                                            sprayData.data?[index].image == null
                                                ? Icon(
                                                    Icons.remove_red_eye,
                                                    color: Color(0xff157173),
                                                  )
                                                : GenericImageLoader(
                                                  imageUrl:
                                                      '${ref.watch(dioProvider).options.baseUrl}/resources/assets/upload/spray/${sprayData.data?[index].image}',
                                                  // For network image
                                                  width: 40,
                                                  height: 40,
                                                  fit: BoxFit.contain,
                                                )
                                          ],
                                        )),
                                  ],
                                ),
                              ),
                              SizedBox(
                                height: 5,
                              ),
                              Container(
                                color: primaryColorDark,
                                padding: const Pad(all: 10),
                                child: IntrinsicHeight(
                                  child: Row(children: [
                                    Expanded(
                                        child: Text(
                                      "Spray Date",
                                      textAlign: TextAlign.center,
                                      style: TextStyle(
                                          fontWeight: FontWeight.bold,
                                          color: Colors.white,
                                          fontSize: Adaptive.sp(14)),
                                    )),
                                    const VerticalDivider(),
                                    Expanded(
                                        child: Text(
                                      "Due Date",
                                      textAlign: TextAlign.center,
                                      style: TextStyle(
                                          fontWeight: FontWeight.bold,
                                          color: Colors.white,
                                          fontSize: Adaptive.sp(14)),
                                    )),
                                    const VerticalDivider(),
                                    Expanded(
                                        child: Text(
                                      "Chemical",
                                      textAlign: TextAlign.center,
                                      style: TextStyle(
                                          fontWeight: FontWeight.bold,
                                          color: Colors.white,
                                          fontSize: Adaptive.sp(14)),
                                    )),
                                    const VerticalDivider(),
                                    Expanded(
                                        child: Text(
                                      "dosage",
                                      textAlign: TextAlign.center,
                                      style: TextStyle(
                                          fontWeight: FontWeight.bold,
                                          color: Colors.white,
                                          fontSize: Adaptive.sp(14)),
                                    )),
                                  ]),
                                ),
                              ),
                              Container(
                                padding: EdgeInsets.symmetric(vertical: 7),
                                child: IntrinsicHeight(
                                  child: Row(children: [
                                    Expanded(
                                        child: Text(
                                      '${sprayData.data?[index].date}'
                                          .substring(0, 10),
                                      textAlign: TextAlign.center,
                                      style: TextStyle(
                                          fontWeight: FontWeight.bold,
                                          color: Colors.black,
                                          fontSize: Adaptive.sp(14)),
                                    )),
                                    const VerticalDivider(),
                                    Expanded(
                                        child: Text(
                                      '${sprayData.data?[index].nextDate}'
                                          .substring(0, 10),
                                      textAlign: TextAlign.center,
                                      style: TextStyle(
                                          fontWeight: FontWeight.bold,
                                          color: Colors.black,
                                          fontSize: Adaptive.sp(14)),
                                    )),
                                    const VerticalDivider(),
                                    Expanded(
                                        child: Text(
                                      '${sprayData.data?[index].chemical}',
                                      textAlign: TextAlign.center,
                                      style: TextStyle(
                                          fontWeight: FontWeight.bold,
                                          color: Colors.black,
                                          fontSize: Adaptive.sp(14)),
                                    )),
                                    const VerticalDivider(),
                                    Expanded(
                                        child: Text(
                                      '${sprayData.data?[index].dose}',
                                      textAlign: TextAlign.center,
                                      style: TextStyle(
                                          fontWeight: FontWeight.bold,
                                          color: Colors.black,
                                          fontSize: Adaptive.sp(14)),
                                    )),
                                  ]),
                                ),
                              ),
                            ],
                          ),
                          // padding: EdgeInsets.all(10),
                          margin: EdgeInsets.all(10),
                          decoration: BoxDecoration(
                            border: Border.all(color: Color(0xff157173)),
                            borderRadius: BorderRadius.circular(10),
                          ),
                        );
                      },
                    )
                  ],
                ),
          error: (e, s) => Text(''),
          loading: () => loader(context)),
    );
  }
}
